spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

server:
  port: 8083

auth:
  jwt:
    secret: "${JWT_SECRET:+Ko8oNC676s6D5pEdWC3BbvvFV/ZYBX1F9gjTU/n5Ts=}"
    issuer: "${JWT_ISSUER:ecommerce-user-service}"
