spring:
  application:
    name: catalog-service
  mongodb:
    uri: "${MONGODB_URI:mongodb://catalog_service:catalog_service_password@localhost:27017/catalog_service_db?authSource=admin}"

server:
  port: 8081

auth:
  jwt:
    secret: "${JWT_SECRET:+Ko8oNC676s6D5pEdWC3BbvvFV/ZYBX1F9gjTU/n5Ts=}"
    issuer: "${JWT_ISSUER:ecommerce-user-service}"
