apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-credentials
  namespace: ecommerce
type: Opaque
stringData:
  catalog-mongodb-username: catalog_service
  catalog-mongodb-password: replace-me
  user-postgres-username: user_service
  user-postgres-password: replace-me
  order-postgres-username: order_service
  order-postgres-password: replace-me
