spring:
  application:
    name: order-service
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5433/order_service_db}"
    username: "${DATABASE_USERNAME:order_service}"
    password: "${DATABASE_PASSWORD:order_service_password}"
  jpa:
    hibernate:
      ddl-auto: "${JPA_DDL_AUTO:update}"
    open-in-view: false

server:
  port: 8082

auth:
  jwt:
    secret: "${JWT_SECRET:+Ko8oNC676s6D5pEdWC3BbvvFV/ZYBX1F9gjTU/n5Ts=}"
    issuer: "${JWT_ISSUER:ecommerce-user-service}"
