apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: atakowiec/order-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://order-postgres:5432/order_service_db
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-credentials
                  key: order-postgres-username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-credentials
                  key: order-postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-credentials
                  key: jwt-secret
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8082
      targetPort: http
