apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: atakowiec/catalog-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-credentials
                  key: catalog-mongodb-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-credentials
                  key: catalog-mongodb-password
            - name: MONGODB_URI
              value: mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@catalog-mongodb:27017/catalog_service_db?authSource=admin
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-credentials
                  key: jwt-secret
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: ecommerce
spec:
  selector:
    app: catalog-service
  ports:
    - name: http
      port: 8081
      targetPort: http
